---
title: Data science as an atomic habit
author: Malcolm Barrett
date: '2021-01-04'
slug: data-science-as-an-atomic-habit
draft: true
categories:
  - learning
  - habits
  - r
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-01-04T08:38:52-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Several years ago, I lived at the Zen Center of New York City, a Zen temple focused on supporting lay practitioners--folks who practice but also have jobs, families, and so on. Living at a Zen center is inherently intensive. You follow the temple schedule--morning and evening meditation, work and meals together, and regular meditation retreats--as well as managing your other responsibilities. Yet, there's a certain ease to practicing meditation in such a place: you don't have to give it a second thought. Everything about places like ZCNYC is set up to support your practice. Your schedule is plainly spelled out for you. If you sleep in (🙋), someone will come get you up so you can join in the meditation hall (😅). Your life *systematically* supports your practice.

When I moved to California for my Ph.D., I had a hard time with my practice. I didn't lack interest or motivation: I knew from direct experience that it was important. But now *I* was responsible for making it happen. After a number of months of struggling with sitting[^sitting] every day, I decided enough was enough. I made a vow: I was going to sit every day for the rest of my life. I didn't make a commitment to a certain amount of hours or any other requirement. I just focused on consistency. 

Making a vow to sit every day completely changed my experience. Why? The answer was clear to me almost immediately: the debate in my head was gone. There was no more "should I sit?", no more "how long?" or "when?". I didn't worry about it, because it was a solved problem: I sit every day, first thing. Nothing to think about. Even though spending *more* time practicing was important to me, I didn't focus on that. I focused on the system that got me on the cushion. Because it's important to me, spending more time doing it bloomed naturally from a consistent practice; if I just got on the cushion every day, that was enough. 

I recently read *Atomic Habits* by James Clear. 

[^sitting]: The term "sitting" is a euphemism for doing meditation. It's especially common in Zen, where we practice [zazen](https://zmm.org/teachings-and-training/meditation-instructions/), a form of silent, seated meditation. In fact, "zazen" can be translated as "seated meditation" or "sitting Zen".